#!/usr/bin/env zsh

if [[ `sudo netstat -tapn | grep :2222 | grep EST | wc -l` -ne 1 ]]

then

    echo 'starting new tunnel'

    autossh -M 20000 -f -N jsn@jsn.homeunix.com -R 4444:localhost:22 -C -p 2222

fi
