#!/usr/bin/env zsh

if [[ `sudo netstat -tapn | grep :2222 | grep EST | wc -l` -ne 1 ]]

then

    echo 'starting new tunnel'

    screen -S tunnel -d -m zsh -lc 'ssh miko@miko.homelinux.com -p 2222 -R 4444:localhost:22'

fi
