#!/usr/bin/env zsh

# kill off existing ethminer process
pkill ethminer
pkill gominer

sleep 3

cd ~/miners/eth-proxy

yes | cp -f etc.conf eth-proxy.conf

~/scripts/start_etceth_proxy

screen -S etc-miner -d -m zsh -lc 'ethminer -R ~/.etchash -F localhost:8080 -G --farm-recheck 200 --cl-local-work 256 --cl-global-work 16384'

~/apps/adl3/atitweak -f 100
