#!/usr/bin/env zsh

pkill -9 ethminer
pkill -9 gominer

yes | cp -f ~/scripts/eth.conf ~/miners/eth-proxy/eth-proxy.conf

~/scripts/start_etceth_proxy

screen -S eth-miner -d -m zsh -lc 'ethminer -R ~/.ethhash -F localhost:8080 -G --farm-recheck 200 --cl-local-work 256 --cl-global-work 16384'
